export const AlphabetSeed = [
    { pronunciation: "ah", nativenm: "A", courseId: 1, order: 1, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/A.mp3" },
    { pronunciation: "beh", nativenm: "B", courseId: 1, order: 2, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/B.mp3" },
    { pronunciation: "seh", nativenm: "C", courseId: 1, order: 3, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/C.mp3" },
    { pronunciation: "deh", nativenm: "D", courseId: 1, order: 4, type: "alphabet", audioSrc: "BasicsBasics/audio/spanish/alpha/D.mp3" },
    { pronunciation: "eh", nativenm: "E", courseId: 1, order: 5, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/E.mp3" },
    { pronunciation: "efe", nativenm: "F", courseId: 1, order: 6, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/F.mp3" },
    { pronunciation: "heh", nativenm: "G", courseId: 1, order: 7, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/G.mp3" },
    { pronunciation: "ah-cheh", nativenm: "H", courseId: 1, order: 8, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/H.mp3" },
    { pronunciation: "ee", nativenm: "I", courseId: 1, order: 9, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/I.mp3" },
    { pronunciation: "ho-tah", nativenm: "J", courseId: 1, order: 10, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/J.mp3" },
    { pronunciation: "kah", nativenm: "K", courseId: 1, order: 11, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/K.mp3" },
    { pronunciation: "eh-leh", nativenm: "L", courseId: 1, order: 12, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/L.mp3" },
    { pronunciation: "eh-meh", nativenm: "M", courseId: 1, order: 13, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/M.mp3" },
    { pronunciation: "eh-neh", nativenm: "N", courseId: 1, order: 14, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/N.mp3" },
    { pronunciation: "enyeh", nativenm: "Ñ", courseId: 1, order: 15, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/Ñ.mp3" },
    { pronunciation: "oh", nativenm: "O", courseId: 1, order: 16, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/O.mp3" },
    { pronunciation: "peh", nativenm: "P", courseId: 1, order: 17, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/P.mp3" },
    { pronunciation: "koo", nativenm: "Q", courseId: 1, order: 18, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/Q.mp3" },
    { pronunciation: "eh-reh", nativenm: "R", courseId: 1, order: 19, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/R.mp3" },
    { pronunciation: "eh-seh", nativenm: "S", courseId: 1, order: 20, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/S.mp3" },
    { pronunciation: "teh", nativenm: "T", courseId: 1, order: 21, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/T.mp3" },
    { pronunciation: "oo", nativenm: "U", courseId: 1, order: 22, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/U.mp3" },
    { pronunciation: "beh", nativenm: "V", courseId: 1, order: 23, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/V.mp3" },
    { pronunciation: "doble veh", nativenm: "W", courseId: 1, order: 24, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/W.mp3" },
    { pronunciation: "eh-kees", nativenm: "X", courseId: 1, order: 25, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/X.mp3" },
    { pronunciation: "yeh", nativenm: "Y", courseId: 1, order: 26, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/Y.mp3" },
    { pronunciation: "seh-tah", nativenm: "Z", courseId: 1, order: 27, type: "alphabet", audioSrc: "Basics/audio/spanish/alpha/Z.mp3" },


    // french alphadet 26 
 
      { pronunciation: "ah", nativenm: "A", courseId: 2, order: 1, type: "alphabet", audioSrc: "Basics/audio/french/alpha/A.mp3" },
      { pronunciation: "beh", nativenm: "B", courseId: 2, order: 2, type: "alphabet", audioSrc: "Basics/audio/french/alpha/B.mp3" },
      { pronunciation: "seh", nativenm: "C", courseId: 2, order: 3, type: "alphabet", audioSrc: "Basics/audio/french/alpha/C.mp3" },
      { pronunciation: "deh", nativenm: "D", courseId: 2, order: 4, type: "alphabet", audioSrc: "Basics/audio/french/alpha/D.mp3" },
      { pronunciation: "uh", nativenm: "E", courseId: 2, order: 5, type: "alphabet", audioSrc: "Basics/audio/french/alpha/E.mp3" },
      { pronunciation: "eff", nativenm: "F", courseId: 2, order: 6, type: "alphabet", audioSrc: "Basics/audio/french/alpha/F.mp3" },
      { pronunciation: "zheh", nativenm: "G", courseId: 2, order: 7, type: "alphabet", audioSrc: "Basics/audio/french/alpha/G.mp3" },
      { pronunciation: "ahsh", nativenm: "H", courseId: 2, order: 8, type: "alphabet", audioSrc: "Basics/audio/french/alpha/H.mp3" },
      { pronunciation: "ee", nativenm: "I", courseId: 2, order: 9, type: "alphabet", audioSrc: "Basics/audio/french/alpha/I.mp3" },
      { pronunciation: "zhee", nativenm: "J", courseId: 2, order: 10, type: "alphabet", audioSrc: "Basics/audio/french/alpha/J.mp3" },
      { pronunciation: "kah", nativenm: "K", courseId: 2, order: 11, type: "alphabet", audioSrc: "Basics/audio/french/alpha/K.mp3" },
      { pronunciation: "ell", nativenm: "L", courseId: 2, order: 12, type: "alphabet", audioSrc: "Basics/audio/french/alpha/L.mp3" },
      { pronunciation: "emm", nativenm: "M", courseId: 2, order: 13, type: "alphabet", audioSrc: "Basics/audio/french/alpha/M.mp3" },
      { pronunciation: "enn", nativenm: "N", courseId: 2, order: 14, type: "alphabet", audioSrc: "Basics/audio/french/alpha/N.mp3" },
      { pronunciation: "oh", nativenm: "O", courseId: 2, order: 15, type: "alphabet", audioSrc: "Basics/audio/french/alpha/O.mp3" },
      { pronunciation: "peh", nativenm: "P", courseId: 2, order: 16, type: "alphabet", audioSrc: "Basics/audio/french/alpha/P.mp3" },
      { pronunciation: "koo", nativenm: "Q", courseId: 2, order: 17, type: "alphabet", audioSrc: "Basics/audio/french/alpha/Q.mp3" },
      { pronunciation: "err", nativenm: "R", courseId: 2, order: 18, type: "alphabet", audioSrc: "Basics/audio/french/alpha/R.mp3" },
      { pronunciation: "ess", nativenm: "S", courseId: 2, order: 19, type: "alphabet", audioSrc: "Basics/audio/french/alpha/S.mp3" },
      { pronunciation: "teh", nativenm: "T", courseId: 2, order: 20, type: "alphabet", audioSrc: "Basics/audio/french/alpha/T.mp3" },
      { pronunciation: "oo", nativenm: "U", courseId: 2, order: 21, type: "alphabet", audioSrc: "Basics/audio/french/alpha/U.mp3" },
      { pronunciation: "veh", nativenm: "V", courseId: 2, order: 22, type: "alphabet", audioSrc: "Basics/audio/french/alpha/V.mp3" },
      { pronunciation: "doo-bluh-veh", nativenm: "W", courseId: 2, order: 23, type: "alphabet", audioSrc: "Basics/audio/french/alpha/W.mp3" },
      { pronunciation: "eeks", nativenm: "X", courseId: 2, order: 24, type: "alphabet", audioSrc: "Basics/audio/french/alpha/X.mp3" },
      { pronunciation: "ee-grek", nativenm: "Y", courseId: 2, order: 25, type: "alphabet", audioSrc: "Basics/audio/french/alpha/Y.mp3" },
      { pronunciation: "zed", nativenm: "Z", courseId: 2, order: 26, type: "alphabet", audioSrc: "Basics/audio/french/alpha/Z.mp3" },



      /// japnese
     
        // Hiragana (あ - ん)
        { pronunciation: "a", nativenm: "H_あ", courseId: 3, order: 1, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/a.mp3" },
        { pronunciation: "i", nativenm: "H_い", courseId: 3, order: 2, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/i.mp3" },
        { pronunciation: "u", nativenm: "H_う", courseId: 3, order: 3, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/u.mp3" },
        { pronunciation: "e", nativenm: "H_え", courseId: 3, order: 4, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/e.mp3" },
        { pronunciation: "o", nativenm: "H_お", courseId: 3, order: 5, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/o.mp3" },
        { pronunciation: "ka", nativenm: "H_か", courseId: 3, order: 6, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/ka.mp3" },
        { pronunciation: "ki", nativenm: "H_き", courseId: 3, order: 7, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/ki.mp3" },
        { pronunciation: "ku", nativenm: "H_く", courseId: 3, order: 8, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/ku.mp3" },
        { pronunciation: "ke", nativenm: "H_け", courseId: 3, order: 9, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/ke.mp3" },
        { pronunciation: "ko", nativenm: "H_こ", courseId: 3, order: 10, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/ko.mp3" },
        { pronunciation: "sa", nativenm: "H_さ", courseId: 3, order: 11, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/sa.mp3" },
        { pronunciation: "shi", nativenm: "H_し", courseId: 3, order: 12, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/shi.mp3" },
        { pronunciation: "su", nativenm: "H_す", courseId: 3, order: 13, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/su.mp3" },
        { pronunciation: "se", nativenm: "H_せ", courseId: 3, order: 14, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/se.mp3" },
        { pronunciation: "so", nativenm: "H_そ", courseId: 3, order: 15, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/so.mp3" },
        { pronunciation: "ta", nativenm: "H_た", courseId: 3, order: 16, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/ta.mp3" },
        { pronunciation: "chi", nativenm: "H_ち", courseId: 3, order: 17, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/chi.mp3" },
        { pronunciation: "tsu", nativenm: "H_つ", courseId: 3, order: 18, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/tsu.mp3" },
        { pronunciation: "te", nativenm: "H_て", courseId: 3, order: 19, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/te.mp3" },
        { pronunciation: "to", nativenm: "H_と", courseId: 3, order: 20, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/to.mp3" },
        { pronunciation: "na", nativenm: "H_な", courseId: 3, order: 21, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/na.mp3" },
        { pronunciation: "ni", nativenm: "H_に", courseId: 3, order: 22, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/ni.mp3" },
        { pronunciation: "nu", nativenm: "H_ぬ", courseId: 3, order: 23, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/nu.mp3" },
        { pronunciation: "ne", nativenm: "H_ね", courseId: 3, order: 24, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/ne.mp3" },
        { pronunciation: "no", nativenm: "H_の", courseId: 3, order: 25, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/no.mp3" },
        { pronunciation: "ha", nativenm: "H_は", courseId: 3, order: 26, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/ha.mp3" },
        { pronunciation: "hi", nativenm: "H_ひ", courseId: 3, order: 27, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/hi.mp3" },
        { pronunciation: "fu", nativenm: "H_ふ", courseId: 3, order: 28, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/fu.mp3" },
        { pronunciation: "he", nativenm: "H_へ", courseId: 3, order: 29, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/he.mp3" },
        { pronunciation: "ho", nativenm: "H_ほ", courseId: 3, order: 30, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/ho.mp3" },
        { pronunciation: "ma", nativenm: "H_ま", courseId: 3, order: 31, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/ma.mp3" },
        { pronunciation: "mi", nativenm: "H_み", courseId: 3, order: 32, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/mi.mp3" },
        { pronunciation: "mu", nativenm: "H_む", courseId: 3, order: 33, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/mu.mp3" },
        { pronunciation: "me", nativenm: "H_め", courseId: 3, order: 34, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/me.mp3" },
        { pronunciation: "mo", nativenm: "H_も", courseId: 3, order: 35, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/mo.mp3" },
        { pronunciation: "ya", nativenm: "H_や", courseId: 3, order: 36, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/ya.mp3" },
        { pronunciation: "yu", nativenm: "H_ゆ", courseId: 3, order: 37, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/yu.mp3" },
        { pronunciation: "yo", nativenm: "H_よ", courseId: 3, order: 38, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/yo.mp3" },
        { pronunciation: "ra", nativenm: "H_ら", courseId: 3, order: 39, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/ra.mp3" },
        { pronunciation: "ri", nativenm: "H_り", courseId: 3, order: 40, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/ri.mp3" },
        { pronunciation: "ru", nativenm: "H_る", courseId: 3, order: 41, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/ru.mp3" },
        { pronunciation: "re", nativenm: "H_れ", courseId: 3, order: 42, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/re.mp3" },
        { pronunciation: "ro", nativenm: "H_ろ", courseId: 3, order: 43, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/ro.mp3" },
        { pronunciation: "wa", nativenm: "H_わ", courseId: 3, order: 44, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/wa.mp3" },
        { pronunciation: "wo", nativenm: "H_を", courseId: 3, order: 45, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/wo.mp3" },
        { pronunciation: "n", nativenm: "H_ん", courseId: 3, order: 46, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/hiragana/n.mp3" },
    
        // Katakana (ア - ン)
        { pronunciation: "a", nativenm: "K_ア", courseId: 3, order: 1, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/a.mp3" },
        { pronunciation: "i", nativenm: "K_イ", courseId: 3, order: 2, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/i.mp3" },
        { pronunciation: "u", nativenm: "K_ウ", courseId: 3, order: 3, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/u.mp3" },
        { pronunciation: "e", nativenm: "K_エ", courseId: 3, order: 4, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/e.mp3" },
        { pronunciation: "o", nativenm: "K_オ", courseId: 3, order: 5, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/o.mp3" },
        { pronunciation: "ka", nativenm: "K_カ", courseId: 3, order: 6, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/ka.mp3" },
        { pronunciation: "ki", nativenm: "K_キ", courseId: 3, order: 7, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/ki.mp3" },
        { pronunciation: "ku", nativenm: "K_ク", courseId: 3, order: 8, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/ku.mp3" },
        { pronunciation: "ke", nativenm: "K_ケ", courseId: 3, order: 9, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/ke.mp3" },
        { pronunciation: "ko", nativenm: "K_コ", courseId: 3, order: 10, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/ko.mp3" },
        { pronunciation: "sa", nativenm: "K_サ", courseId: 3, order: 11, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/sa.mp3" },
        { pronunciation: "shi", nativenm: "K_シ", courseId: 3, order: 12, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/shi.mp3" },
        { pronunciation: "su", nativenm: "K_ス", courseId: 3, order: 13, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/su.mp3" },
        { pronunciation: "se", nativenm: "K_セ", courseId: 3, order: 14, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/se.mp3" },
        { pronunciation: "so", nativenm: "K_ソ", courseId: 3, order: 15, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/so.mp3" },
        { pronunciation: "ta", nativenm: "K_タ", courseId: 3, order: 16, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/ta.mp3" },
        { pronunciation: "chi", nativenm: "K_チ", courseId: 3, order: 17, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/chi.mp3" },
        { pronunciation: "tsu", nativenm: "K_ツ", courseId: 3, order: 18, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/tsu.mp3" },
        { pronunciation: "te", nativenm: "K_テ", courseId: 3, order: 19, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/te.mp3" },
        { pronunciation: "to", nativenm: "K_ト", courseId: 3, order: 20, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/to.mp3" },
        { pronunciation: "na", nativenm: "K_ナ", courseId: 3, order: 21, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/na.mp3" },
        { pronunciation: "ni", nativenm: "K_ニ", courseId: 3, order: 22, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/ni.mp3" },
        { pronunciation: "nu", nativenm: "K_ヌ", courseId: 3, order: 23, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/nu.mp3" },
        { pronunciation: "ne", nativenm: "K_ネ", courseId: 3, order: 24, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/ne.mp3" },
        { pronunciation: "no", nativenm: "K_ノ", courseId: 3, order: 25, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/no.mp3" },
        { pronunciation: "ha", nativenm: "K_ハ", courseId: 3, order: 26, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/ha.mp3" },
        { pronunciation: "hi", nativenm: "K_ヒ", courseId: 3, order: 27, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/hi.mp3" },
        { pronunciation: "fu", nativenm: "K_フ", courseId: 3, order: 28, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/fu.mp3" },
        { pronunciation: "he", nativenm: "K_ヘ", courseId: 3, order: 29, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/he.mp3" },
        { pronunciation: "ho", nativenm: "K_ホ", courseId: 3, order: 30, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/ho.mp3" },
        { pronunciation: "ma", nativenm: "K_マ", courseId: 3, order: 31, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/ma.mp3" },
        { pronunciation: "mi", nativenm: "K_ミ", courseId: 3, order: 32, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/mi.mp3" },
        { pronunciation: "mu", nativenm: "K_ム", courseId: 3, order: 33, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/mu.mp3" },
        { pronunciation: "me", nativenm: "K_メ", courseId: 3, order: 34, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/me.mp3" },
        { pronunciation: "mo", nativenm: "K_モ", courseId: 3, order: 35, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/mo.mp3" },
        { pronunciation: "ya", nativenm: "K_ヤ", courseId: 3, order: 36, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/ya.mp3" },
        { pronunciation: "yu", nativenm: "K_ユ", courseId: 3, order: 37, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/yu.mp3" },
        { pronunciation: "yo", nativenm: "K_ヨ", courseId: 3, order: 38, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/yo.mp3" },
        { pronunciation: "ra", nativenm: "K_ラ", courseId: 3, order: 39, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/ra.mp3" },
        { pronunciation: "ri", nativenm: "K_リ", courseId: 3, order: 40, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/ri.mp3" },
        { pronunciation: "ru", nativenm: "K_ル", courseId: 3, order: 41, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/ru.mp3" },
        { pronunciation: "re", nativenm: "K_レ", courseId: 3, order: 42, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/re.mp3" },
        { pronunciation: "ro", nativenm: "K_ロ", courseId: 3, order: 43, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/ro.mp3" },
        { pronunciation: "wa", nativenm: "K_ワ", courseId: 3, order: 44, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/wa.mp3" },
        { pronunciation: "wo", nativenm: "K_ヲ", courseId: 3, order: 45, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/wo.mp3" },
        { pronunciation: "n", nativenm: "K_ン", courseId: 3, order: 46, type: "alphabet", audioSrc: "Basics/audio/japanese/alpha/katakana/n.mp3" },



        // marathi alpha
        { pronunciation: "a", nativenm: "अ", courseId: 4, order: 1, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/अ.mp3" },
  { pronunciation: "aa", nativenm: "आ", courseId: 4, order: 2, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/आ.mp3" },
  { pronunciation: "i", nativenm: "इ", courseId: 4, order: 3, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/इ.mp3" },
  { pronunciation: "ii", nativenm: "ई", courseId: 4, order: 4, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/ई.mp3" },
  { pronunciation: "u", nativenm: "उ", courseId: 4, order: 5, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/उ.mp3" },
  { pronunciation: "uu", nativenm: "ऊ", courseId: 4, order: 6, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/ऊ.mp3" },
  { pronunciation: "ru", nativenm: "ऋ", courseId: 4, order: 7, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/ऋ.mp3" },
  { pronunciation: "e", nativenm: "ए", courseId: 4, order: 8, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/ए.mp3" },
  { pronunciation: "ai", nativenm: "ऐ", courseId: 4, order: 9, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/ऐ.mp3" },
  { pronunciation: "o", nativenm: "ओ", courseId: 4, order: 10, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/ओ.mp3" },
  { pronunciation: "au", nativenm: "औ", courseId: 4, order: 11, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/औ.mp3" },
  { pronunciation: "an", nativenm: "अं", courseId: 4, order: 12, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/अं.mp3" },
  { pronunciation: "ah", nativenm: "अः", courseId: 4, order: 13, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/अः.mp3" },
  { pronunciation: "ka", nativenm: "क", courseId: 4, order: 14, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/क.mp3" },
  { pronunciation: "kha", nativenm: "ख", courseId: 4, order: 15, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/ख.mp3" },
  { pronunciation: "ga", nativenm: "ग", courseId: 4, order: 16, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/ग.mp3" },
  { pronunciation: "gha", nativenm: "घ", courseId: 4, order: 17, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/घ.mp3" },
  { pronunciation: "nga", nativenm: "ङ", courseId: 4, order: 18, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/ङ.mp3" },
  { pronunciation: "cha", nativenm: "च", courseId: 4, order: 19, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/च.mp3" },
  { pronunciation: "chha", nativenm: "छ", courseId: 4, order: 20, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/छ.mp3" },
  { pronunciation: "ja", nativenm: "ज", courseId: 4, order: 21, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/ज.mp3" },
  { pronunciation: "jha", nativenm: "झ", courseId: 4, order: 22, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/झ.mp3" },
  { pronunciation: "nya", nativenm: "ञ", courseId: 4, order: 23, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/ञ.mp3" },
  { pronunciation: "ta", nativenm: "ट", courseId: 4, order: 24, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/ट.mp3" },
  { pronunciation: "tha", nativenm: "ठ", courseId: 4, order: 25, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/ठ.mp3" },
  { pronunciation: "da", nativenm: "ड", courseId: 4, order: 26, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/ड.mp3" },
  { pronunciation: "dha", nativenm: "ढ", courseId: 4, order: 27, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/ढ.mp3" },
  { pronunciation: "na", nativenm: "ण", courseId: 4, order: 28, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/ण.mp3" },
  { pronunciation: "ta", nativenm: "त", courseId: 4, order: 29, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/त.mp3" },
  { pronunciation: "tha", nativenm: "थ", courseId: 4, order: 30, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/थ.mp3" },
  { pronunciation: "da", nativenm: "द", courseId: 4, order: 31, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/द.mp3" },
  { pronunciation: "dha", nativenm: "ध", courseId: 4, order: 32, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/ध.mp3" },
  { pronunciation: "na", nativenm: "न", courseId: 4, order: 33, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/न.mp3" },
  { pronunciation: "pa", nativenm: "प", courseId: 4, order: 34, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/प.mp3" },
  { pronunciation: "pha", nativenm: "फ", courseId: 4, order: 35, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/फ.mp3" },
  { pronunciation: "ba", nativenm: "ब", courseId: 4, order: 36, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/ब.mp3" },
  { pronunciation: "bha", nativenm: "भ", courseId: 4, order: 37, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/भ.mp3" },
  { pronunciation: "ma", nativenm: "म", courseId: 4, order: 38, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/म.mp3" },
  { pronunciation: "ya", nativenm: "य", courseId: 4, order: 39, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/य.mp3" },
  { pronunciation: "ra", nativenm: "र", courseId: 4, order: 40, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/र.mp3" },
  { pronunciation: "la", nativenm: "ल", courseId: 4, order: 41, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/ल.mp3" },
  { pronunciation: "va", nativenm: "व", courseId: 4, order: 42, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/व.mp3" },
  { pronunciation: "sha", nativenm: "श", courseId: 4, order: 43, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/श.mp3" },
  { pronunciation: "shha", nativenm: "ष", courseId: 4, order: 44, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/ष.mp3" },
  { pronunciation: "sa", nativenm: "स", courseId: 4, order: 45, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/स.mp3" },
  { pronunciation: "ha", nativenm: "ह", courseId: 4, order: 46, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/ह.mp3" },
  { pronunciation: "laa", nativenm: "ळ", courseId: 4, order: 47, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/ळ.mp3" },
  { pronunciation: "ksha", nativenm: "क्ष", courseId: 4, order: 48, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/क्ष.mp3" },
  { pronunciation: "gya", nativenm: "ज्ञ", courseId: 4, order: 49, type: "alphabet", audioSrc: "/Basics/audio/marathi/alpha/ज्ञ.mp3" },
    
  
  ];
  
  
  